export const STORAGE_KEYS = {
  CURRENT_READ: "bible_current_read",
  CURRENT_STUDY: "bible_current_study",
  CURRENT_SEARCH: "bible_current_search",
  SEARCH_HISTORY: "bible_search_history",
  HIGHLIGHTS: "bible_highlights",
  NOTES: "bible_notes",
  STUDIES: "bible_studies",
  AUTO_BACKUP: "bible_auto_backup",
  AUTO_BACKUP_FILE_URI: "bible_auto_backup_file_uri",
  DARK_MODE: "bible_dark_mode",
  BIBLE_VERSION_GLOBAL: "bible_version_global",
  VIEW_MODE_VERSION: "bible_view_mode_version",
  VIEW_MODE_BOOK: "bible_view_mode_book",
  VIEW_MODE_STUDY_VERSE: "bible_view_mode_study_verse",
  FONT_SIZE: "bible_font_size",
  TEXT_ALIGN: "bible_text_align",
  READER_THEME: "bible_reader_theme",
  READER_FONT: "bible_reader_font",
  SHOW_TITLES: "bible_show_titles",
  SHOW_VERSE_NUMBERS: "bible_show_verse_numbers",
  APP_COLOR_THEME: "bible_app_color_theme",
  HAPTICS_ENABLED: "bible_haptics_enabled",
  LAST_ROUTE: "bible_last_route",
  LAST_ROUTE_PARAMS: "bible_last_route_params",
  APP_CLEARED: "bible_app_cleared",
  BIBLE_HISTORY: "bible_history",
  BIBLE_COMPARE: "bible_compare",
  READING_PLAN: "bible_reading_plan",
  READING_PLAN_NOTIFICATIONS_ENABLED:
    "bible_reading_plan_notifications_enabled",
  READING_PLAN_NOTIFICATION_TIME: "bible_reading_plan_notification_time",
  AUDIO_VOICE: "bible_audio_voice",
  AUDIO_CONTINUOUS_PLAYBACK: "bible_audio_continuous_playback",
  AUDIO_AUTO_SCROLL: "bible_audio_auto_scroll",
  DOWNLOAD_QUEUE: "bible_download_queue",
};
